### ISSUE TITLE
Invalid return value

### ISSUE THREAD

**Issue by sowmeashree** [theryansmee/install-jest-angular-8#23]
I am using Angular 8 and following the steps here is giving me some error. I couldn't really connect what's behind this error. 

`● Invalid return value:
      Code transformer's `process` method must return an object containing `code` key
      with processed string. If `processAsync` method is implemented it must return
      a Promise resolving to an object containing `code` key with processed string.
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation`
      
Kindly help me to figure out what's causing this error. Also let me know if you need any more inputs from me.

**Comment by sowmeashree** [comment]
After I did some configuration changes, now I am in a place where the test cases are failing for below reason.

` FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    ReferenceError: Injectable is not defined

      1 | import { Injectable } from '@angular/core';
    > 2 | import { RouterTestingModule } from '@angular/router/testing';
        | ^
      3 | import { TestBed } from '@angular/core/testing';
      4 |
      5 | import { AppComponent } from './app.component';

      at node_modules/@angular/common/bundles/common.umd.js:536:15
      at Object.<anonymous> (src/app/app.component.spec.ts:2:1)`
      
Please guide me here ( I am new to angular so apologies if this is silly )
@theryansmee
